In [1]:
import numpy as np

In [4]:
A = np.array([[1,-1],[6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [9]:
b = np.array([[1],[3]])
b

array([[1],
       [3]])

(2, 1)

In [16]:
A @ b

array([[-2],
       [18]])

In [11]:
eig_val, eig_vec = np.linalg.eig(A)

In [12]:
eig_val

array([2.5+1.93649167j, 2.5-1.93649167j])

In [13]:
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])