In [1]:
import numpy as np

1. Buatlah vektor di bawah ini dengan Python: 17 22 19

In [3]:
A = np.array([17,22,19])
A

array([17, 22, 19])

2. Diberikan 3 buah vector 3 dimensi:
𝑨 =
17
22
19
,𝑩 =
10
20
11
, 𝑪 =
5
12
9
Hitunglah:
- A+B
- B-C
- A dot C
- A x B
- norm A
- Sudut antara vektor A dan B

In [4]:
B = np.array([10,20,11])
C = np.array([5,12,9])

In [5]:
B

array([10, 20, 11])

In [6]:
C

array([ 5, 12,  9])

In [7]:
A + B

array([27, 42, 30])

In [8]:
B - C

array([5, 8, 2])

In [10]:
A.dot(C)

520

In [13]:
A @ B

819

In [14]:
np.linalg.norm(A)

33.67491648096547

In [17]:
np.linalg.norm(A,1) #secara manhattan


58.0

In [19]:
costheta = A @ B / (np.linalg.norm(A) * np.linalg.norm(B))
costheta

0.9759590023331435

In [21]:
rad = np.arccos(costheta)
rad

0.21971776576153962

In [23]:
sudut = np.degrees(rad)
sudut

12.588900662180242