In [1]:
import numpy as np

In [3]:
t1 = np.array([[23,50],[7,12]])
t2 = np.array([[57,67],[99,43]])
t3 = np.array([[75,21],[57,12]])
t4 = np.array([[87,26],[18,84]])

In [8]:
tensor = np.array([t1,t2,t3,t4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [9]:
tensor.shape

(4, 2, 2)

In [12]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])

In [13]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [14]:
B

array([17, 22, 19])

In [15]:
A @ B

array([1852, 2454, 4305])

In [43]:
x = np.array([[23,50,19],[7,12,109],[57,67,98]])
x

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [44]:
x.shape

(3, 3)

In [42]:
A3.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [51]:
np.linalg.det(x)

131344.0000000002

In [66]:
xinv = np.linalg.inv(x)
xinv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [67]:
x @ xinv

array([[ 1.00000000e+00, -3.64291930e-17,  1.81495444e-16],
       [-3.46944695e-17,  1.00000000e+00,  4.05491613e-17],
       [ 9.71445147e-17,  8.67361738e-17,  1.00000000e+00]])